[tool.poetry]
name = "check-the-weather"
version = "0.1.0"
description = "Dynamic weather data retrieval."
authors = ["Jonathan Rooke"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
